name: Deploy Google Cloud Function
on: push
jobs:
  deploy-cloud-function:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3
      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v0'
        with:
          name: 'quizlet-to-flashcards'
          runtime: 'python38'
          region: 'us-east4'
          entry_point: 'home'
          https_trigger_security_level: 'secure_optional'

      - id: 'test'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
